chore: validate NuGet packages using dotnet-validate

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,12 +10,12 @@ on:
     branches:
       - main
 
+env:
+  NUGET_PACKAGES: '${{ github.workspace }}/.nuget/packages'
+
 jobs:
   build:
     runs-on: ubuntu-latest
-
-    env:
-      NUGET_PACKAGES: '${{ github.workspace }}/.nuget/packages'
 
     steps:
       - name: Checkout
@@ -35,6 +35,7 @@ jobs:
 
       - name: Setup .NET
         uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4
+        id: setup-dotnet
 
       - name: Restore .NET Tools
         run: |
@@ -59,6 +60,12 @@ jobs:
           path: ${{ github.workspace }}/artifacts/packages
           if-no-files-found: error
 
+      - name: Output .NET Tool Versions
+        id: tool-versions
+        run: |
+          dotnetValidateVersion=$(jq .tools["dotnet-validate"].version ./.config/dotnet-tools.json)
+          echo "dotnet-validate-version=$dotnetValidateVersion" >> "$GITHUB_OUTPUT"
+
       - name: Publish NuGet packages
         if: startsWith(github.ref, 'refs/tags/v')
         run: |
@@ -66,3 +73,44 @@ jobs:
             --nuget-api-key $NUGET_API_KEY
         env:
           NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
+
+    outputs:
+      dotnet-sdk-version: ${{ steps.setup-dotnet.outputs.dotnet-version }}
+      dotnet-validate-version: ${{ steps.tool-versions.outputs.dotnet-validate-version }}
+
+  validate-packages:
+    runs-on: ubuntu-latest
+    needs: build
+
+    steps:
+      - name: Download Packages
+        uses: actions/download-artifact@v4
+        with:
+          name: packages
+
+      - name: Setup .NET
+        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4
+        with:
+          dotnet-version: ${{ needs.build.outputs.dotnet-sdk-version }}
+
+      - name: Install .NET Tools
+        run: |
+          dotnet tool install --global dotnet-validate --version ${env.DOTNET_VALIDATE_VERSION}
+        env:
+          DOTNET_VALIDATE_VERSION: ${{ needs.build.outputs.dotnet-validate-version }}
+
+      - name: Validate Packages
+        run: |
+          fail_count=0
+
+          for file in "${{ github.workspace }}/packages"/*.nupkg; do
+            dotnet validate package local $file
+            if [ $? -ne 0 ]; then
+              ((fail_count++))
+            fi
+          done
+
+          if [ $fail_count -ne 0 ]; then
+            echo "::error::Validation failed for $fail_count NuGet package(s)"
+            exit 1
+          fi
