chore: validate NuGet packages using dotnet-validate (#20)
Co-authored-by: Raphael Strotz <Xzelsius@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,12 +10,12 @@ on:
     branches:
       - main
 
+env:
+  NUGET_PACKAGES: '${{ github.workspace }}/.nuget/packages'
+
 jobs:
   build:
     runs-on: ubuntu-latest
-
-    env:
-      NUGET_PACKAGES: '${{ github.workspace }}/.nuget/packages'
 
     steps:
       - name: Checkout
@@ -35,6 +35,7 @@ jobs:
 
       - name: Setup .NET
         uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4
+        id: setup-dotnet
 
       - name: Restore .NET Tools
         run: |
@@ -59,8 +60,83 @@ jobs:
           path: ${{ github.workspace }}/artifacts/packages
           if-no-files-found: error
 
+      - name: Output .NET Tool Versions
+        id: tool-versions
+        run: |
+          dotnet_validate_version=$(jq -r '.tools["dotnet-validate"].version' ./.config/dotnet-tools.json)
+          echo "dotnet-validate-version=$dotnet_validate_version" >> $GITHUB_OUTPUT
+
+    outputs:
+      dotnet-sdk-version: ${{ steps.setup-dotnet.outputs.dotnet-version }}
+      dotnet-validate-version: ${{ steps.tool-versions.outputs.dotnet-validate-version }}
+
+  validate-packages:
+    runs-on: ubuntu-latest
+    needs: build
+
+    steps:
+      - name: Download Packages
+        uses: actions/download-artifact@v4
+        with:
+          name: packages
+
+      - name: Setup .NET
+        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4
+        with:
+          dotnet-version: ${{ needs.build.outputs.dotnet-sdk-version }}
+
+      - name: Install .NET Tools
+        run: |
+          dotnet tool install \
+            --global \
+            --version $DOTNET_VALIDATE_VERSION \
+            dotnet-validate
+        env:
+          DOTNET_VALIDATE_VERSION: ${{ needs.build.outputs.dotnet-validate-version }}
+
+      - name: Validate Packages
+        run: |
+          fail_count=0
+
+          for file in "${{ github.workspace }}/*.nupkg"; do
+            dotnet validate package local $file
+            if [ $? -ne 0 ]; then
+              ((fail_count++))
+            fi
+          done
+
+          if [ $fail_count -ne 0 ]; then
+            echo "::error::Validation failed for $fail_count NuGet package(s)"
+            exit 1
+          fi
+
+  publish-packages:
+    runs-on: ubuntu-latest
+    needs: [build, validate-packages]
+
+    # Only publish if build was triggered for a tag
+    if: startsWith(github.ref, 'refs/tags/v')
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
+        with:
+          fetch-depth: 1
+
+      - name: Download Packages
+        uses: actions/download-artifact@v4
+        with:
+          name: packages
+          path: ${{ github.workspace }}/artifacts/packages
+
+      - name: Setup .NET
+        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4
+
+      - name: Restore .NET Tools
+        run: |
+          dotnet tool restore
+
       - name: Publish NuGet packages
-        if: startsWith(github.ref, 'refs/tags/v')
         run: |
           dotnet nuke Publish \
             --nuget-api-key $NUGET_API_KEY
